<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>usr183MLScoreboard</name>
  <uuid>5314ab35-681a-4bb7-896b-f598495ffda7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to predict( 'Input mapping' ) ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
